sudo: false
language: node_js
node_js:
  - stable
script: 
  - npm test
after_success:
  - npm run report-coverage
  deploy:
  provider: heroku
  api_key:
    secure: "cec6193c-d20d-4701-82bf-30f1c72c3402"